name: offer_show
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_picker: ^2.0.3
  badges: ^2.0.2
  characters: ^1.2.0
  flutter_vibrate: ^1.3.0
  vibration: ^1.7.3
  image_picker: ^0.8.4+10
  file_picker: ^4.5.0
  flutter:
    sdk: flutter
  photo_view: ^0.10.2
  provider:
  shared_preferences: ^2.0.5
  fluttertoast: ^8.0.6
  flutter_svg: ^0.21.0+1
  dio: ^4.0.0
  url_launcher: ^6.0.20
  heic_to_jpg: ^0.2.0
  image_gallery_saver: ^1.7.1
  octo_image: ^1.0.1
  flutter_cache_manager: ^3.3.0
  cached_network_image_platform_interface: ^1.0.0
  cached_network_image_web: ^1.0.0
  crop_your_image: ^0.7.2
  share_plus: ^4.0.4
  lottie: ^1.3.0
  flutter_bounce: ^1.1.0
  syncfusion_flutter_sliders: ^20.1.51
  sticky_headers: ^0.2.0
  adaptive_theme: ^3.0.0
  animate_do: ^2.1.0
  percent_indicator: ^4.2.2
  html: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/emoji/1/
    - lib/emoji/2/
    - lib/img/
    - lib/img/banner/
    - lib/img/setting/
    - lib/img/square/
    - lib/img/person/
    - lib/img/home/
    - lib/img/msg/
    - lib/img/me/
    - lib/img/me_dark/
    - lib/collect_btn/
    - lib/page/msg_three/
    - lib/lottie/
    - lib/img/about/1.png
    - lib/img/explore/
    - lib/img/topic_dark_func/
