name: offer_show
description: A new Flutter project.

publish_to: "none"
version: 1.0.10+2

environment:
  sdk: ">=2.7.0 <=3.0.0"

dependencies:
  wechat_camera_picker: ^3.7.0
  flutter_staggered_grid_view: ^0.6.2
  # webview_flutter: ^4.0.6
  flutter_keyboard_visibility: ^5.4.0
  route_transitions: ^2.0.1
  screenshot: ^1.2.3
  # flutter_qr_reader: ^1.0.5
  bitsdojo_window: ^0.1.5
  window_manager: ^0.2.7
  images_picker: ^1.2.11
  flick_video_player: ^0.5.0
  video_player: ^2.4.6
  qr_code_scanner: ^1.0.0
  qr_flutter: ^4.0.0
  device_info_plus: ^9.0.0
  sizer: ^2.0.15
  flutter_picker: ^2.0.3
  badges: ^2.0.2
  characters: ^1.2.0
  flutter_vibrate: ^1.3.0
  vibration: ^1.7.3
  image_picker: ^0.8.5+3
  file_picker: ^5.2.5
  flutter:
    sdk: flutter
  photo_view: ^0.14.0
  provider:
  shared_preferences: ^2.0.5
  fluttertoast: ^8.0.6
  flutter_svg: ^0.21.0+1
  dio: ^4.0.0
  url_launcher: ^6.0.20
  heic_to_jpg: ^0.2.0
  image_gallery_saver: ^1.7.1
  octo_image: ^1.0.1
  flutter_cache_manager: ^3.3.0
  cached_network_image_platform_interface: ^1.0.0
  cached_network_image_web: ^1.0.0
  crop_your_image: ^0.7.2
  share_plus: ^4.0.4
  lottie: ^1.3.0
  flutter_bounce: ^1.1.0
  syncfusion_flutter_sliders: ^20.1.51
  sticky_headers: ^0.2.0
  adaptive_theme: ^3.0.0
  animate_do: ^2.1.0
  percent_indicator: ^4.2.2
  html: ^0.15.0
  # flutter_gifimage: ^1.0.1
  bubble_tab_indicator: ^0.1.6
  pull_to_refresh: ^2.0.0
  flutter_displaymode: ^0.4.0
  path_provider: ^2.0.11
  wakelock: ^0.6.2
  chewie: ^1.3.4
  device_info: ^2.0.3
  permission_handler: ^10.2.0
  webview_flutter: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # fonts:
  #   - family: MiSans
  #     fonts:
  #       - asset: lib/font/MiSans-Regular.ttf
  assets:
    # - lib/font/
    - lib/img/celebration/
    - lib/emoji/1/
    - lib/emoji/2/
    - lib/emoji/3/
    - lib/emoji/4/
    - lib/img/
    - lib/img/water_total/
    - lib/img/banner/
    - lib/img/setting/
    - lib/img/square/
    - lib/img/square/column/
    - lib/img/person/
    - lib/img/home/
    - lib/img/msg/
    - lib/img/me/
    - lib/img/me_dark/
    - lib/page/hot/img/
    - lib/collect_btn/
    - lib/page/msg_three/
    - lib/lottie/
    - lib/img/explore/
    - lib/img/topic_dark_func/
  
